STEER_STRAIGHT_DC = 7.5
STEER_LEFT_DC = 10
STEER_RIGHT_DC = 5

# Max values
NEUTRAL_SPEED_DC = 7.5
FORWARD_SPEED_DC = 10
BACKWARD_SPEED_DC = 5

THROTTLE_PIN = 19
STEER_PIN = 18

THROTTLE_FREQ = 50
STEER_FREQ = 50